# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rforce-raygao}
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Raymond Gao"]
  s.date = %q{2010-11-28}
  s.description = %q{An temporary patch of the RForce 0.4.1, increased the DEFAULT_BATCH_SIZE from 10 to 2000, max allowed by the SF platform, see Web Services API guide for detail. }
  s.email = %q{raygao2000@yahoo.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bugs/issue-09d998dc3f9d6e8928598fd5d9c6627102dedd65.yaml",
     "bugs/issue-1b668248120eb4fd055f0ea6b75ff807f6955936.yaml",
     "bugs/issue-3ef7a7c5c7e38fb76e1f53e1b67f45559e21b104.yaml",
     "bugs/issue-a7a87cb98d29943a49d1608adb68475838ad2e65.yaml",
     "bugs/issue-c92d34e10038ba6b9acfd7e3dfb2b154e463baba.yaml",
     "bugs/project.yaml",
     "lib/rforce-raygao.rb",
     "lib/rforce.rb",
     "lib/rforce/binding.rb",
     "lib/rforce/binding.rb.zip",
     "lib/rforce/method_keys.rb",
     "lib/rforce/soap_pullable.rb",
     "lib/rforce/soap_response.rb",
     "lib/rforce/soap_response_expat.rb",
     "lib/rforce/soap_response_hpricot.rb",
     "lib/rforce/soap_response_rexml.rb",
     "lib/rforce/version.rb",
     "rforce-raygao.gemspec",
     "spec/rforce_spec.rb",
     "spec/soap-response.xml",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/timing.rake",
     "test/helper.rb",
     "test/test_rforce-raygao.rb",
     "wsdl/README.html",
     "wsdl/README.txt",
     "wsdl/ca.pem",
     "wsdl/default.rb",
     "wsdl/defaultDriver.rb",
     "wsdl/orderedhash.rb",
     "wsdl/partner.wsdl.xml",
     "wsdl/sample/create.rb",
     "wsdl/sample/describeGlobal.rb",
     "wsdl/sample/describeSObjects.rb",
     "wsdl/sample/getServerTimestamp.rb",
     "wsdl/sample/query.rb",
     "wsdl/sample/queryMore.rb",
     "wsdl/sample/retrieve.rb",
     "wsdl/sforceDriver.rb",
     "wsdl/soap/property",
     "wsdl/wsdl.rb"
  ]
  s.homepage = %q{http://github.com/raygao/rforce-raygao}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An temporary patch of the RForce 0.4.1, increased the DEFAULT_BATCH_SIZE from 10 to 2000}
  s.test_files = [
    "spec/rforce_spec.rb",
     "spec/spec_helper.rb",
     "test/helper.rb",
     "test/test_rforce-raygao.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, [">= 0.4.4"])
    else
      s.add_dependency(%q<oauth>, [">= 0.4.4"])
    end
  else
    s.add_dependency(%q<oauth>, [">= 0.4.4"])
  end
end

