--- !ditz.rubyforge.org,2008-03-06/project 
name: rforce
version: "0.3"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: rforce
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-07-28 05:35:54.153742 Z
    - Ian Dees <undees@gmail.com>
    - created
    - Will be ready for ActiveSalesforce.
